from enum import Enum

categorical_fields = [
    "film_simulation",
    "sensor",
    "dynamic_range",
    "grain_effect",
    "color_chrome_effect",
    "color_chrome_effect_blue",
    "white_balance",
]

numeric_fields = {
    "highlight": {
        "range": (-2, 4),
        "normalize": lambda x: x / 4,
        "denormalize": lambda x: int(round(x * 4)),
        "format": lambda x: f"+{x}" if x > 0 else str(x),
    },
    "shadow": {
        "range": (-2, 4),
        "normalize": lambda x: x / 4,
        "denormalize": lambda x: int(round(x * 4)),
        "format": lambda x: f"+{x}" if x > 0 else str(x),
    },
    "color": {
        "range": (-4, 4),
        "normalize": lambda x: x / 4,
        "denormalize": lambda x: int(round(x * 4)),
        "format": lambda x: f"+{x}" if x > 0 else str(x),
    },
    "sharpening": {
        "range": (-4, 4),
        "normalize": lambda x: x / 4,
        "denormalize": lambda x: int(round(x * 4)),
        "format": lambda x: f"+{x}" if x > 0 else str(x),
    },
    "noise_reduction": {
        "range": (-4, 4),
        "normalize": lambda x: x / 4,
        "denormalize": lambda x: int(round(x * 4)),
        "format": lambda x: f"+{x}" if x > 0 else str(x),
    },
    "clarity": {
        "range": (-5, 5),
        "normalize": lambda x: x / 5,
        "denormalize": lambda x: int(round(x * 5)),
        "format": lambda x: f"+{x}" if x > 0 else str(x),
    },
    "wb_shift_red": {
        "range": (-9, 9),
        "normalize": lambda x: x / 9,
        "denormalize": lambda x: int(round(x * 9)),
        "format": lambda x: f"+{x}" if x > 0 else str(x),
    },
    "wb_shift_blue": {
        "range": (-9, 9),
        "normalize": lambda x: x / 9,
        "denormalize": lambda x: int(round(x * 9)),
        "format": lambda x: f"+{x}" if x > 0 else str(x),
    },
    "exposure_compensation": {
        "range": (-3, 3),
        "normalize": lambda x: x / 3,
        "denormalize": lambda x: round(x * 3, 1),  # Keep one decimal
        "format": lambda x: f"+{x:.1f}" if x > 0 else f"{x:.1f}",
    },
}

mappings = {
    "film_simulation": {
        "indices": {
            "": 0,
            "Classic Chrome": 1,
            "Classic Negative": 2,
            "Velvia": 3,
            "Eterna": 4,
            "Acros": 5,
            "Monochrome": 6,
            "Acros+R": 7,
            "Sepia": 8,
            "PRO Neg. Std": 9,
            "PRO Neg. Hi": 10,
            "Provia": 11,
            "Astia": 12,
            "Acros+G": 13,
            "Monochrome+G": 14,
            "Eterna Bleach Bypass": 15,
            "Acros+Y": 16,
            "Monochrome+R": 17,
            "Nostalgic Neg.": 18,
            "Reala Ace": 19,
        },
        "frequencies": {
            "": 0,
            "Classic Chrome": 554,
            "Classic Negative": 275,
            "Velvia": 149,
            "Eterna": 160,
            "Acros": 130,
            "Monochrome": 89,
            "Acros+R": 30,
            "Sepia": 21,
            "PRO Neg. Std": 234,
            "PRO Neg. Hi": 65,
            "Provia": 195,
            "Astia": 100,
            "Acros+G": 30,
            "Monochrome+G": 30,
            "Eterna Bleach Bypass": 90,
            "Acros+Y": 10,
            "Monochrome+R": 5,
            "Nostalgic Neg.": 95,
            "Reala Ace": 50,
        },
    },
    "sensor": {
        "indices": {
            "": 0,
            "X-Trans IV": 1,
            "X-Trans V": 2,
            "X-Trans III": 3,
            "X-Trans II": 4,
            "X-Trans I": 5,
            "Bayer": 6,
            "GFX": 7,
            "EXR-CMOS": 8,
        },
        "frequencies": {
            "": 0,
            "X-Trans IV": 1171,
            "X-Trans V": 503,
            "X-Trans III": 352,
            "X-Trans II": 163,
            "X-Trans I": 73,
            "Bayer": 25,
            "GFX": 15,
            "EXR-CMOS": 10,
        },
    },
    "dynamic_range": {
        "indices": {
            "": 0,
            "DR200": 1,
            "DR400": 2,
            "DR-Auto": 3,
            "DR100": 4,
            "DR-P Auto": 5,
            "DR-P Strong": 6,
        },
        "frequencies": {
            "": 5,
            "DR200": 768,
            "DR400": 1202,
            "DR-Auto": 152,
            "DR100": 145,
            "DR-P Auto": 25,
            "DR-P Strong": 15,
        },
    },
    "grain_effect": {
        "indices": {
            "": 0,
            "Weak Small": 1,
            "Strong Small": 2,
            "Strong Large": 3,
            "Off": 4,
            "Weak Large": 5,
            "Strong": 6,
            "Weak": 7,
        },
        "frequencies": {
            "": 271,
            "Weak Small": 405,
            "Strong Small": 335,
            "Strong Large": 316,
            "Off": 50,
            "Weak Large": 145,
            "Strong": 395,
            "Weak": 395,
        },
    },
    "color_chrome_effect": {
        "indices": {"": 0, "Strong": 1, "Weak": 2, "Off": 3},
        "frequencies": {"": 630, "Strong": 980, "Weak": 185, "Off": 517},
    },
    "color_chrome_effect_blue": {
        "indices": {"": 0, "Weak": 1, "Strong": 2, "Off": 3},
        "frequencies": {"": 1091, "Weak": 420, "Strong": 410, "Off": 391},
    },
    "white_balance": {
        "indices": {
            "": 0,
            "Daylight": 1,
            "Auto": 2,
            "5200K": 3,
            "6050K": 4,
            "5600K": 5,
            "Fluorescent 1": 6,
            "7100K": 7,
            "4550K": 8,
            "Fluorescent 3": 9,
            "2750K": 10,
            "5900K": 11,
            "Shade": 12,
            "2650K": 13,
            "8300K": 14,
            "Fluorescent 2": 15,
            "6300K": 16,
            "4300K": 17,
            "3200K": 18,
            "10000K": 19,
            "7700K": 20,
            "2500K": 21,
            "Custom Daylight": 22,
            "6700K": 23,
            "4500K": 24,
            "Daylight/Fine": 25,
            "Incandescent": 26,
            "4200K": 27,
            "4700K": 28,
            "5500K": 29,
            "7000K": 30,
            "5250K": 31,
            "8700K": 32,
            "Auto White Priority": 33,
            "Auto Ambience Priority": 34,
            "7350K": 35,
            "4900K": 36,
            "6990K": 37,
            "3000K": 38,
            "2950K": 39,
            "5000K": 40,
            "5300K": 41,
            "6900K": 42,
            "9100K": 43,
            "4800K": 44,
            "7300K": 45,
            "5800K": 46,
            "6800K": 47,
            "6400K": 48,
            "5100K": 49,
            "3400K": 50,
            "2900K": 51,
            "6000K": 52,
            "6500K": 53,
            "4350K": 54,
            "5150K": 55,
            "Underwater": 56,
            "6600K": 57,
            "3100K": 58,
        },
        "frequencies": {
            "": 0,
            "Daylight": 410,
            "Auto": 732,
            "5200K": 30,
            "6050K": 5,
            "5600K": 10,
            "Fluorescent 1": 80,
            "7100K": 20,
            "4550K": 5,
            "Fluorescent 3": 65,
            "2750K": 10,
            "5900K": 30,
            "Shade": 80,
            "2650K": 10,
            "8300K": 5,
            "Fluorescent 2": 45,
            "6300K": 30,
            "4300K": 15,
            "3200K": 35,
            "10000K": 30,
            "7700K": 25,
            "2500K": 10,
            "Custom Daylight": 5,
            "6700K": 25,
            "4500K": 10,
            "Daylight/Fine": 60,
            "Incandescent": 50,
            "4200K": 5,
            "4700K": 15,
            "5500K": 45,
            "7000K": 10,
            "5250K": 15,
            "8700K": 15,
            "Auto White Priority": 75,
            "Auto Ambience Priority": 20,
            "7350K": 10,
            "4900K": 15,
            "6990K": 5,
            "3000K": 10,
            "2950K": 5,
            "5000K": 30,
            "5300K": 25,
            "6900K": 5,
            "9100K": 25,
            "4800K": 5,
            "7300K": 5,
            "5800K": 25,
            "6800K": 10,
            "6400K": 5,
            "5100K": 10,
            "3400K": 10,
            "2900K": 5,
            "6000K": 10,
            "6500K": 15,
            "4350K": 10,
            "5150K": 10,
            "Underwater": 15,
            "6600K": 10,
            "3100K": 5,
        },
    },
    "iso": {
        "indices": {
            "": 0,
            "up to ISO 6400": 1,
            "1600 to 6400": 2,
            "1600 to 12800": 3,
            "up to ISO 12800": 4,
            "up to ISO 3200": 5,
            "3200 to 6400": 6,
            "3200 to 12800": 7,
            "25600 to 51200": 8,
            "12800": 9,
            "3200": 10,
            "up to ISO 5000": 11,
            "up to ISO 1600": 12,
        },
        "frequencies": {
            "": 0,
            "up to ISO 6400": 1778,
            "1600 to 6400": 10,
            "1600 to 12800": 20,
            "up to ISO 12800": 175,
            "up to ISO 3200": 229,
            "3200 to 6400": 5,
            "3200 to 12800": 20,
            "25600 to 51200": 5,
            "12800": 15,
            "3200": 20,
            "up to ISO 5000": 5,
            "up to ISO 1600": 30,
        },
    },
}

films_by_sensor = {
    "X-Trans IV": [
        "Classic Negative",
        "Sepia",
        "Provia",
        "Astia",
        "Acros+G",
        "Monochrome",
        "Monochrome+G",
        "Eterna Bleach Bypass",
        "Acros",
        "Velvia",
        "Eterna",
        "Acros+Y",
        "PRO Neg. Std",
        "Classic Chrome",
        "Acros+R",
        "PRO Neg. Hi",
    ],
    "X-Trans V": [
        "Classic Negative",
        "Sepia",
        "Provia",
        "Astia",
        "Acros+G",
        "Reala Ace",
        "Monochrome",
        "Monochrome+G",
        "Nostalgic Neg.",
        "Acros",
        "Eterna Bleach Bypass",
        "Velvia",
        "Eterna",
        "Acros+Y",
        "PRO Neg. Std",
        "Classic Chrome",
        "Acros+R",
        "PRO Neg. Hi",
    ],
    "X-Trans III": [
        "Sepia",
        "Provia",
        "Acros+G",
        "Astia",
        "Monochrome",
        "Acros",
        "Velvia",
        "Eterna",
        "PRO Neg. Std",
        "Classic Chrome",
        "Acros+R",
        "PRO Neg. Hi",
    ],
    "X-Trans II": [
        "Sepia",
        "Provia",
        "Astia",
        "Monochrome",
        "Velvia",
        "Monochrome+R",
        "PRO Neg. Std",
        "Classic Chrome",
        "PRO Neg. Hi",
    ],
    "X-Trans I": ["Sepia", "Provia", "Astia", "Monochrome", "Velvia", "PRO Neg. Std"],
    "Bayer": ["Sepia", "Provia", "Monochrome", "Velvia", "Classic Chrome"],
    "GFX": ["Provia", "Classic Chrome", "Classic Negative"],
    "EXR-CMOS": ["Provia"],
}


class SensorModel(Enum):
    XTransI = "X-Trans I"
    XTransII = "X-Trans II"
    XTransIII = "X-Trans III"
    XTransIV = "X-Trans IV"
    XTransV = "X-Trans V"
    Bayer = "Bayer"
    GFX = "GFX"
    EXR = "EXR-CMOS"
    Unknown = "Unknown"


ignored_fields_by_sensor = {
    SensorModel.XTransI: [
        "sensor",
        "color_chrome_effect",
        "color_chrome_effect_blue",
        "clarity",
    ],
    SensorModel.XTransII: [
        "sensor",
        "color_chrome_effect",
        "color_chrome_effect_blue",
        "clarity",
    ],
    SensorModel.XTransIII: [
        "sensor",
        "color_chrome_effect",
        "color_chrome_effect_blue",
        "clarity",
    ],
    SensorModel.XTransIV: ["sensor"],
    SensorModel.XTransV: ["sensor"],
    SensorModel.Bayer: [
        "sensor",
        "color_chrome_effect",
        "color_chrome_effect_blue",
        "clarity",
    ],
    SensorModel.GFX: ["sensor"],
    SensorModel.EXR: [
        "sensor",
        "color_chrome_effect",
        "color_chrome_effect_blue",
        "clarity",
    ],
}
